label: 'Test Form'
endpoint: 'genericCase'
allowed_sites: ['US', 'CA', 'DK', 'SE', 'NO']
fields:
  test_field:
    type: 'textfield'
    required: true
    label: 'Test Field'
    help_text: 'This is a test field'
    api_object: 'customer'
    api_name: 'TestField'
    validation:
      length:
        min: 1
        max: 100