label: RECEIPT REQUEST
endpoint: 'genericCase'
allowed_sites:
  - us
fields:
  topic:
    required: TRUE
    default_value: 'RECEIPT REQUEST'
  subject:
    required: TRUE
    default_value: 'RECEIPT REQUEST'
  record_type:
    required: TRUE
    default_value: 'Feedback & Complaints'
  quick_name:
    required: true
  quick_email:
    required: true
  quick_phone:
    required: true
  case_category:
    required: TRUE
    default_value: 'Station'
  case_subcategory:
    required: TRUE
    default_value: 'Receipt request'
  customer_type:
    required: TRUE
    default_value: 'B2C'
  case_number:
    required: true
  station:
    required: true
  case_origin:
    required: TRUE
    default_value: 'Web'