label: RECEIPT REQUEST
endpoint: 'genericCase'
allowed_sites:
  - us
fields:
  topic:
    required: TRUE
    default_value: 'RECEIPT REQUEST'
  subject:
    required: TRUE
    default_value: 'RECEIPT REQUEST'
  record_type:
    required: TRUE
    default_value: 'Feedback & Complaints'
  quick_name:
    required: true
  quick_email:
    required: true
  quick_phone:
    required: true
  case_category:
    required: TRUE
    default_value: 'Station'
  case_subcategory:
    required: TRUE
    default_value: 'Receipt request'
  item1:
    markup: 'Purchase details'
  datetime_of_1st_occurence:
    required: true
  customer_type:
    required: TRUE
    default_value: 'B2C'
  station:
    required: true
  item2:
    markup: 'Payment information'
  payment_method:
    required: TRUE
    values:
      'Cash': 'Cash'
      'Card': 'Card'
#    icons:
#      'Cash': 189
#      'Card': 27
  amount:
    required: TRUE
  first_6_digits:
    required: TRUE
    visibility:
      ':input[data-id="payment_method"]': { value: 'Card' }
  last_4_digits:
    required: TRUE
    visibility:
      ':input[data-id="payment_method"]': { value: 'Card' }
  case_origin:
    required: TRUE
    default_value: 'Web'
  terms_of_use:
    markup: '<a href="https://www.circlek.com/terms-of-use" target="_blank">Terms of Use</a>'
  privacy_policy:
    markup: '<a href="https://www.circlek.com/privacy-policy" target="_blank">Privacy Policy</a>'
  case_number:
    required: false