label: RECEIPT REQUEST
endpoint: 'genericCase'
allowed_sites:
  - us
fields:
  customerBusinessUnit:
    required: TRUE
  leadSource:
    required: TRUE
    default_value: 'Website'
  leadFormName:
    required: TRUE
    default_value: 'RECEIPT REQUEST'
  quick_name:
    required: true
  quick_email:
    required: true
  quick_phone:
    required: true
  datetime_of_1st_occurence:
    required: true

