label: Receipt Request
endpoint: 'genericCase'
allowed_sites:
  - us
fields:
  quick_name:
    required: true
  quick_email:
    required: true
  quick_phone:
    required: true
  datetime_of_1st_occurence:
    required: true
    
