label: 'Support Request Form'
endpoint: 'genericCase'
allowed_sites: ['US', 'CA', 'DK', 'SE', 'NO']
fields:
  firstName:
    type: 'textfield'
    required: true
    label: 'First Name'
    help_text: 'Enter your first name'
  lastName:
    type: 'textfield'
    required: true
    label: 'Last Name'
    help_text: 'Enter your last name'
  email:
    type: 'email'
    required: true
    label: 'Email Address'
    pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
    pattern_hint: 'Please enter a valid email address'
  phone:
    type: 'telprefix'
    required: false
    label: 'Phone Number'
    help_text: 'Enter your phone number'
  company:
    type: 'textfield'
    required: false
    label: 'Company Name'
    help_text: 'Enter your company name'
  subject:
    type: 'textfield'
    required: true
    label: 'Subject'
    help_text: 'Brief description of your issue'
    maxlength: 200
  message:
    type: 'textarea'
    required: true
    label: 'Detailed Description'
    help_text: 'Please provide detailed information about your issue'
    maxlength: 2000
  priority:
    type: 'select'
    required: true
    label: 'Priority Level'
    help_text: 'Select the priority of your request'
    values:
      low: 'Low'
      medium: 'Medium'
      high: 'High'
      urgent: 'Urgent'