label: 'Contact Form'
endpoint: 'genericCase'
allowed_sites: ['US', 'CA', 'DK', 'SE', 'NO']
fields:
  firstName:
    type: 'textfield'
    required: true
    label: 'First Name'
    help_text: 'Enter your first name'
  lastName:
    type: 'textfield'
    required: true
    label: 'Last Name'
    help_text: 'Enter your last name'
  email:
    type: 'email'
    required: true
    label: 'Email Address'
    pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
    pattern_hint: 'Please enter a valid email address'
  phone:
    type: 'telprefix'
    required: false
    label: 'Phone Number'
    help_text: 'Enter your phone number'
    telprefix_prefix_by_field: countryCode
  company:
    type: 'textfield'
    required: false
    label: 'Company Name'
    help_text: 'Enter your company name'
  message:
    type: 'textarea'
    required: true
    label: 'Message'
    help_text: 'Please describe your inquiry'
    maxlength: 1000